name: Maven Set up
description: "Storage Maven Dependencies"
inputs:
  saludo:
    description: Saludo final
    required: true
    default: Saludando desde un composite action
outputs:
  saludo-usado:
    description: Que saludo se usó al final?
    value: ${{steps.saludo_usado.sal}}
    
runs:
  using: composite
  steps:
    - name: install jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{env.JAVA_VERSION}}
    - name: Set up Maven
      run: |
        java -version
        sudo apt-get update
        sudo apt install maven -y
        mvn -v
      shell: bash
    - name: cache maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Saludo con Maven
      id: saludo_usado
      run: |
        echo ${{inputs.saludo}}
        echo "sal=${{inputs.saludo}}" >> $GITHUB_OUTPUT
      shell: bash