name: Artifacts WF
on: [push]
jobs:
  Generate-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate Artifact"
        run: echo "Sample Artifact!! Bon Jovi 4 Ever" > file.txt
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-jm # Por defecto es artifact
          path: file.txt

  Get-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: my text file
          path: file.txt
      - name: Show Artifact
        run: |
          ls
          cat file.txt
    needs: Generate-Artifact
          
