name: Artifacts WF
on: [push, workflow_dispatch]
jobs:
  Generate-Artifact:
    runs-on: ubuntu-latest
    outputs:
      test-output: ${{steps.gen-output.var}} 
    steps:
      - name: "Generate Artifact"
        run: echo "Sample Artifact!! Bon Jovi 4 Ever" > file.txt
      - name: "Generate Output"
        id: gen-output  
        run: echo "var=Bon Jovi" >> $GITHUB_OUTPUT 
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-jm # Por defecto es artifact
          path: file.txt

  Get-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-jm  # Debe ser igual al artefacto original
        #   path: file.txt
      - name: Show Artifact
        run: |
          ls
          cat file.txt
      - name: Print output
        env:
          OUTPUT1: ${{needs.Generate-Artifact.outputs.test-output}}
        run: |
          #   variable=${{needs.Generate-Artifact.outputs.test-output}}
          echo $OUTPUT1
    needs: Generate-Artifact
  
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
          
