name: conditionals
on: [push, workflow_dispatch]
jobs:

  cond-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        id: step1
        run: echo "step 1" && exit 1
      - name: step2
        run: echo "se ejecuta solo si falla el step 1"
        if: failure() && steps.step1.outcome == 'failure'       
      - name: step3
        run: echo "Step 3"

