name: Containers WF

on: 
  push:
  workflow_dispatch:

jobs:
  
  container-job:
    runs-on: ubuntu-latest
    services:
      docker-dind:
        image: docker:28-dind
    container:
      image: node:18
      env:
        ALBUM: New Jersey
    steps:
      - name: Say Hi
        run: |
          echo "Bon Jovi 4 Ever!"
          echo $ALBUM

