name: Containers WF

on: 
  push:
  workflow_dispatch:

jobs:
  
  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Say Hi
        run: echo "Bon Jovi 4 Ever!"