name: JS Actions

on:
  - push
  - workflow_dispatch

jobs:
  
  JS-Init-Job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Node Deps
        run: |
          cd .github/actions/js-actions
          npm i @actions/core @actions/github @actions/exec
      - name: Saludo desde JS Actions!
        uses: ./.github/actions/js-actions
    