name: manven workflow
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up Maven
      run: |
        java -version
        sudo apt-get update
        sudo apt install maven -y
        sudo mvn -v
    - name: compile
      run: maven compile
    
  