name: maven workflow
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: maven-setup
      uses: ./.github/actions/maven-setup
      env:
        JAVA_VERSION: 21
    - name: compile
      run: mvn compile
  
  install:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: maven-setup
      uses: ./.github/actions/maven-setup
    - name: install
      run: mvn install
    needs: compile
  