name: manven workflow
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up Maven
      run: |
        MAVEN_VERSION=3.9.6
        wget https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
        tar -xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz
        sudo mv apache-maven-${MAVEN_VERSION} /opt/maven
        echo "MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
        echo "/opt/maven/bin" >> $GITHUB_PATH
        maven -version
    - name: compile
      run: maven compile
    
  