name: Reusable WF
on: 
  workflow_call:
    inputs:
      name:
        type: string
        description: "Is the name to say hi"
        required: true
        default: Bon Jovi
    secrets:
      secret-jm:
        required: false
    outputs:
      final-result:
        description: "Final result of the Reusable WF"
        value: ${{jobs.Greet.outputs.result-output}}
        
jobs:
  Greet:
    outputs:
      result-output: ${{steps.step-result.outputs.result}}
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "Hello World From another WF!! ${{inputs.name}} "
      - name: Show Result
        id: step-result
        run: echo "result=success" >> "$GITHUB_OUTPUT"

