name: Reusable WF
on: 
  workflow_call:
    inputs:
      name:
        type: string
        description: "Is the name to say hi"
        required: true
        default: Bon Jovi
    secrets:
      secret-jm:
        required: true
jobs:
  Greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "Hello World From another WF!! ${{inputs.name}} "

