name: Implement Reusable WF
on: [push, workflow_dispatch]

jobs:
  Greet:
    uses: ./.github/workflows/reusable-wf.yml
    with:
      name: Juan Manuel
    # secrets:
    #   secret-jm: ${{secrets.secret-jm}}
