name: Implement Reusable WF
on: [push, workflow_dispatch]

jobs:
  Greet:
    uses: ./.github/workflows/reusable-wf.yml
    with:
      name: Juan Manuel
    # secrets:
    #   secret-jm: ${{secrets.secret-jm}}
  Print-Reusable-Output:
    runs-on: ubuntu-latest
    steps:
      - name: print result
        run: echo "the result was ${{needs.Greet.outputs.result-output}}"
    needs: Greet
